#ifndef GAMEMODE_H
#define	GAMEMODE_H

enum GAME_MODE { GAME_MODE_NONE,
        SINGLE, CLASSIC, TEAM, SURVIVE,
        GAME_MODE_LOCAL, GAME_MODE_SERVER, GAME_MODE_CLIENT,
        EXIT };

enum GAME_PLACE { LOCAL, SERVER, CLIENT };

enum GAME_GOAL { GOAL_NOTHING, GOAL_KILL, GOAL_MONSTER, GOAL_TEAM };

#endif
